# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jaded Reality
email: cmcfee@kent.edu
description: > # this means to ignore newlines until "baseurl:"
  Just another blog from a technologist that works at a fortune 500
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mickfeech.github.io/" # the base hostname & protocol for your site
twitter_username: mickfeech
github_username:  mickfeech

# Build settings
markdown: kramdown
